classSOA/myrottenpotatoes/config/routes.rb
Myrottenpotatoes::Application.routes.draw do

   post '/movies/search_tmdb'
   resources :movies do
      resources :reviews
   end
   root :to => redirect('/movies')
   devise_for :moviegoers, :controllers => { :omniauth_callbacks => "moviegoers/omniauth_callbacks" }
   
end

classSOA/myrottenpotatoes/app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  before_save :capitalize_title
  
  scope :with_good_reviews, lambda { |threshold|
    Movie.joins(:reviews).group(:movie_id).
      having(['AVG(reviews.potatoes) > ?', threshold])
  }
  scope :for_kids, lambda {
    Movie.where('rating in ?', %w(G PG))
  }
  scope :recently_reviewed, lambda { |n|
    Movie.joins(:reviews).where(['reviews.created_at >= ?', n.days.ago]).uniq
  }

  def capitalize_title
    self.title = self.title.split(/\s+/).map(&:downcase).
      map(&:capitalize).join(' ')
  end

 def self.all_ratings ; %w[G PG PG-13 R NC-17] ; end #  shortcut: array of strings
  validates :title, :presence => true
  validates :release_date, :presence => true
  validate :released_1930_or_later # uses custom validator below
  validates :rating, :inclusion => {:in => Movie.all_ratings},
    :unless => :grandfathered?
  def released_1930_or_later
    errors.add(:release_date, 'must be 1930 or later') if
      self.release_date < Date.parse('1 Jan 1930')
  end
  @@grandfathered_date = Date.parse('1 Nov 1968')
  def grandfathered? ; self.release_date >= @@grandfathered_date ; end
end

classSOA/myrottenpotatoes/app/models/moviegoer.rb
class Moviegoer < ActiveRecord::Base
  has_many :reviews
  has_many :movies, :through => :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :provider, :uid, :name
  # attr_accessible :title, :body
  attr_accessor :email

 def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
  moviegoer = Moviegoer.where(:provider => auth.provider, :uid => auth.uid).first
  unless moviegoer
    moviegoer = Moviegoer.create(name:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20]
                         )
  end
  moviegoer
 end
 def self.new_with_session(params, session)
    super.tap do |moviegoer|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        moviegoer.email = data["email"] if moviegoer.email.blank?
      end
    end
  end
end

classSOA/myrottenpotatoes/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :movie
  belongs_to :moviegoer
  attr_protected :moviegoer_id # see text
  # review is valid only if it's associated with a movie:
  validates :movie_id, :presence => true
  # can ALSO require that the referenced movie itself be valid
  #  in order for the review to be valid:
  validates_associated :movie
end

classSOA/myrottenpotatoes/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  

#before_filter :set_current_user
  #protected # prevents method from being invoked by a route
  #def set_current_user
    # we exploit the fact that find_by_id(nil) returns nil
    #@current_user ||= Moviegoer.find_by_id(session[:user_id])
    #redirect_to login_path and return unless @current_user
  #end
  
  # somewhat contrived example of an around-filter
  #around_filter :only => ['withdraw_money', 'transfer_money'] do
  # log who is trying to move money around
  #start = Time.now
  #yield   # do the action
  # note how long it took
  #logger.info params
  #logger.info (Time.now - start)
  #end

   protect_from_forgery

end

classSOA/myrottenpotatoes/app/controllers/moviegoers/omniauth_callbacks_controller.rb
class Moviegoers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/moviegoer.rb)
    @moviegoer = Moviegoer.find_for_facebook_oauth(request.env["omniauth.auth"], current_moviegoer)

    if @moviegoer.persisted?
      sign_in_and_redirect @moviegoer, :event => :authentication #this will throw if @moviegoer is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_moviegoer_registration_url
    end
  end
end

classSOA/myrottenpotatoes/app/controllers/movies_controller.rb
# This file is app/controllers/movies_controller.rb
class MoviesController < ApplicationController
#before_filter :authenticate_moviegoer!  

def index
    @movies = Movie.all
  end
  
  def show
   id = params[:id] # retrieve movie ID from URI route
   @movie = Movie.find(id) # look up movie by unique ID
   # will render app/views/movies/show.html.haml by default
  end
   
 
def create
  @movie = Movie.new(params[:movie])
  if @movie.save
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  else
    render 'new' # note, 'new' template can access @movie's field values!
  end
end

# replaces the 'update' method in controller:

def update
  @movie = Movie.find params[:id]
  if @movie.update_attributes(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  else
    render 'edit' # note, 'edit' template can access @movie's field values!
  end
end

# as a reminder, here is the original 'new' method:
def new
  @movie = Movie.new
end



  def edit
   @movie = Movie.find params[:id]
  end


  def destroy
  @movie = Movie.find(params[:id])
  @movie.destroy
  flash[:notice] = "Movie '#{@movie.title}' deleted."
  redirect_to movies_path
end

  def movies_with_good_reviews
    @movies = Movie.joins(:reviews).group(:movie_id).
      having('AVG(reviews.potatoes) > 3')
  end
  def movies_for_kids
    @movies = Movie.where('rating in ?', %w(G PG))
  end

  def movies_with_filters
    @movies = Movie.with_good_reviews(params[:threshold])
    @movies = @movies.for_kids          if params[:for_kids]
    @movies = @movies.with_many_fans    if params[:with_many_fans]
    @movies = @movies.recently_reviewed if params[:recently_reviewed]
  end
  # or even DRYer:
  def movies_with_filters_2
    @movies = Movie.with_good_reviews(params[:threshold])
    %w(for_kids with_many_fans recently_reviewed).each do |filter|
      @movies = @movies.send(filter) if params[filter]
    end
  end
  
  def search_tmdb
  # hardwire to simulate failure
  flash[:warning] = "'#{params[:search_terms]}' was not found in TMDb."
  redirect_to movies_path
  end
end

classSOA/myrottenpotatoes/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :has_moviegoer_and_movie, :only => [:new, :create]
  protected
  def has_moviegoer_and_movie
    if !(moviegoer_signed_in?)
      flash[:warning] = 'You must be logged in to create a review.'
      redirect_to login_path
    end
    unless (@movie = Movie.find_by_id(params[:movie_id]))
      flash[:warning] = 'Review must be for an existing movie.'
      redirect_to movies_path
    end
  end
  public
  def new
    @review = @movie.reviews.build
  end
  def create
    # since moviegoer_id is a protected attribute that won't get
    # assigned by the mass-assignment from params[:review], we set it
    # by using the << method on the association.  We could also
    # set it manually with review.moviegoer = @current_user.
    current_moviegoer.reviews << @movie.reviews.build(params[:review])
    redirect_to movie_path(@movie)
  end
end

classSOA/myrottenpotatoes/app/helpers/application_helper.rb
module ApplicationHelper
end

classSOA/myrottenpotatoes/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myrottenpotatoes</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

classSOA/myrottenpotatoes/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

 
  %body
    - if moviegoer_signed_in?
      = link_to 'log_out', destroy_moviegoer_session_path, :method => 'delete'
    - else
      = link_to 'login', new_moviegoer_session_path

    -# this goes just inside %body:
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    = yield

classSOA/myrottenpotatoes/app/views/moviegoers/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

classSOA/myrottenpotatoes/app/views/movies/_movie.html.haml
-# A single row of the All Movies table
%tr
  %td= movie.title
  %td= movie.rating
  %td= movie.release_date
  %td= link_to "More about #{movie.title}", movie_path(movie)

classSOA/myrottenpotatoes/app/views/movies/_movie_form.html.haml
- unless @movie.errors.empty?
  #warning
    Errors prevented this movie from being #{controller.action_name}d:
    %ul
      - @movie.errors.full_messages.each do |error|
        %li= error



-# in _movie_form.html.haml (the partial)
 
= label :movie, :title, 'Title'
= text_field :movie, 'title'
 
= label :movie, :rating, 'Rating'
= select :movie, :rating, Movie.all_ratings
 
= label :movie, :release_date, 'Released On'
= date_select :movie, :release_date

classSOA/myrottenpotatoes/app/views/movies/edit.html.haml
-# edit.html.haml using partial
 
%h2 Edit Existing Movie
 
= form_tag movie_path(@movie), :method => :put do
  = render :partial => 'movie_form'
  = submit_tag 'Update Movie Info'

classSOA/myrottenpotatoes/app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Movies

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title
        %td= movie.rating
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

-# add to end of index.html.haml
 
= link_to 'Add new movie', new_movie_path
= link_to 'Movie Title', movies_path

%h1 Search TMDb for a movie
 
= form_tag :action => 'search_tmdb' do
 
  %label{:for => 'search_terms'} Search Terms
  = text_field_tag 'search_terms'
  = submit_tag 'Search TMDb'

classSOA/myrottenpotatoes/app/views/movies/new.html.haml
%h2 Create New Movie
 
= form_tag '/movies', :method => :post do
  = render :partial => 'movie_form'
  = submit_tag 'Save Changes'

classSOA/myrottenpotatoes/app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml
 
%h2 Details about #{@movie.title}
 
%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")
 
%h3 Description:
 
%p#description= @movie.description
 

= link_to 'Back to movie list', movies_path

-# Our Edit link from previous example:
= link_to 'Edit info', edit_movie_path(@movie)

= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'

= link_to 'Add Review', new_movie_review_path(@movie)

classSOA/myrottenpotatoes/app/views/reviews/new.html.haml
%h1 New Review for #{@movie.title}
 
= form_tag movie_reviews_path(@movie) do
  %label How many potatoes:
  = select_tag 'review[potatoes]', options_for_select(1..5)
  = submit_tag 'Create Review'